
export const books = [
    {
        id: 1,
        author: "Chinua Achebe",
        country: "Nigeria",
        imageLink: "https://m.media-amazon.com/images/I/91NtvTU0xEL.jpg",
        language: "English",
        link: "https://en.wikipedia.org/wiki/Things_Fall_Apart",
        pages: 209,
        title: "Things Fall Apart",
        year: 1958,
        description: "A powerful novel about the clash between traditional African culture and colonialism.",
        price: 12.99,
        category: "Fiction",
        rating: 3,
    },
    {
        id: 2,
        author: "Yuval Noah Harari",
        country: "Israel",
        imageLink: "https://m.media-amazon.com/images/I/713jIoMO3UL.jpg",
        language: "English",
        link: "https://en.wikipedia.org/wiki/Sapiens:_A_Brief_History_of_Humankind",
        pages: 443,
        title: "Sapiens: A Brief History of Humankind",
        year: 2011,
        description: "A deep dive into the history and impact of humankind on the world.",
        price: 14.99,
        category: "Non-Fiction",
        rating: 4,
    },
    {
        id: 3,
        author: "Isaac Asimov",
        country: "USA",
        imageLink: "https://m.media-amazon.com/images/I/71UypkUjStL.jpg",
        language: "English",
        link: "https://en.wikipedia.org/wiki/Foundation_(Asimov_novel)",
        pages: 255,
        title: "Foundation",
        year: 1951,
        description: "A sci-fi epic about the rise and fall of civilizations in a galactic empire.",
        price: 10.99,
        category: "Sci-Fi",
        rating: 4,

    },
    {
        id: 4,
        author: "Agatha Christie",
        country: "UK",
        imageLink: "https://m.media-amazon.com/images/I/71pOMFWk7sL._AC_UF1000,1000_QL80_.jpg",
        language: "English",
        link: "https://en.wikipedia.org/wiki/And_Then_There_Were_None",
        pages: 272,
        title: "And Then There Were None",
        year: 1939,
        description: "A classic mystery novel where ten strangers are trapped on an island.",
        price: 9.99,
        category: "Mystery",
        rating: 4,

    },
    {
        id: 5,
        author: "J.R.R. Tolkien",
        country: "UK",
        imageLink: "https://m.media-amazon.com/images/I/81t2CVWEsUL.jpg",
        language: "English",
        link: "https://en.wikipedia.org/wiki/The_Lord_of_the_Rings",
        pages: 1137,
        title: "The Lord of the Rings",
        year: 1954,
        description: "A fantasy masterpiece about the battle against Sauron and the journey to destroy the One Ring.",
        price: 18.99,
        category: "Fantasy",
        rating: 3,

    },
    {
        id: 6,
        author: "Jane Austen",
        country: "UK",
        imageLink: "https://m.media-amazon.com/images/I/712P0p5cXIL._AC_UF1000,1000_QL80_.jpg",
        language: "English",
        link: "https://en.wikipedia.org/wiki/Pride_and_Prejudice",
        pages: 432,
        title: "Pride and Prejudice",
        year: 1813,
        description: "A timeless romance novel exploring love, class, and social expectations.",
        price: 8.99,
        category: "Romance",
        rating: 4,

    },
    {
        id: 7,
        author: "Harper Lee",
        country: "USA",
        imageLink: "https://m.media-amazon.com/images/I/81gepf1eMqL.jpg",
        language: "English",
        link: "https://en.wikipedia.org/wiki/To_Kill_a_Mockingbird",
        pages: 281,
        title: "To Kill a Mockingbird",
        year: 1960,
        description: "A novel about racial injustice in the Deep South seen through the eyes of a young girl.",
        price: 10.99,
        category: "Fiction",
        rating: 4,

    },
    {
        id: 8,
        author: "Stephen Hawking",
        country: "UK",
        imageLink: "https://m.media-amazon.com/images/I/81pQPZAFWbL.jpg",
        language: "English",
        link: "https://en.wikipedia.org/wiki/A_Brief_History_of_Time",
        pages: 256,
        title: "A Brief History of Time",
        year: 1988,
        description: "A groundbreaking book that explains complex physics concepts in simple terms.",
        price: 13.99,
        category: "Non-Fiction",
        rating: 4,

    },
    {
        id: 9,
        author: "Frank Herbert",
        country: "USA",
        imageLink: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQ0e091V2JGmD4EggIicFYngbUlYpCTfgR4mD4jKaMzCvQbnzniD-jYqiS89Pqno8wqLU_jYL9NeEjLkMgMRL8U6rFVb0s-nuZDzvcNCTt7lX2Pj5yrDEfGKQ&usqp=CAE",
        language: "English",
        link: "https://en.wikipedia.org/wiki/Dune_(novel)",
        pages: 412,
        title: "Dune",
        year: 1965,
        description: "A sci-fi epic about politics, religion, and ecology on the desert planet Arrakis.",
        price: 15.99,
        category: "Sci-Fi",
        rating: 4,

    },
    {
        id: 10,
        author: "Arthur Conan Doyle",
        country: "UK",
        imageLink: "https://res.cloudinary.com/bloomsbury-atlas/image/upload/w_568,c_scale,dpr_1.5/jackets/9781847494962.jpg",
        language: "English",
        link: "https://en.wikipedia.org/wiki/The_Hound_of_the_Baskervilles",
        pages: 248,
        title: "The Hound of the Baskervilles",
        year: 1902,
        description: "A famous Sherlock Holmes mystery involving a legendary ghostly hound.",
        price: 7.99,
        category: "Mystery",
        rating: 4,

    }
];

